name: VerifyDocker

on:
  workflow_dispatch:

jobs:
  prep:
    outputs:
      matrix: ${{ steps.set-docker-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - id: set-docker-matrix
        run: |
          echo matrix='{ "image": ["one", "two"] }' >> $GITHUB_OUTPUT

  buildDocker:
    needs: [ prep ]
    strategy:
      matrix: ${{ fromJSON(needs.prep.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Build image
        uses: docker/build-push-action@v6.7.0
        with:
          context: '{{defaultContext}}:src/${{ matrix.image }}'
          push: false
          tags: ${{ matrix.image }}
          outputs: type=docker,dest=/tmp/${{ matrix.image }}.tar

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image }}
          path: /tmp/${{ matrix.image }}.tar

  verifyDocker:
    needs: [ buildDocker ]
    runs-on: ubuntu-latest
    steps:
      - name: Download image 1
        uses: actions/download-artifact@v4
        with:
          name: one
          path: /tmp

      - name: Download image 2
        uses: actions/download-artifact@v4
        with:
          name: two
          path: /tmp

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run images
        run: |
          docker load --input /tmp/one.tar
          docker load --input /tmp/two.tar
          docker image ls
          cd src
          docker compose up

  pushDocker:
    needs: [ prep, verifyDocker ]
    strategy:
      matrix: ${{ fromJSON(needs.prep.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - name: Download image
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.image }}
          path: /tmp

      - name: Load image in Docker
        run: |
          docker load --input /tmp/${{ matrix.image }}.tar
          docker image ls

      - name: Push image
        uses: docker/build-push-action@v6.7.0
        with:
          context: '{{defaultContext}}:src/${{ matrix.image }}'
          push: true
          tags: ${{ matrix.image }}:latest
